Release: 4.0

diff --git a/tmux-workspace b/tmux-workspace
--- a/tmux-workspace
+++ b/tmux-workspace
@@ -2,6 +2,42 @@
 
 showhelp=0
 
+#===============================================================================
+# help text, if the function is called with any kind of parameter
+#===============================================================================
+function print_help {
+echo "usage: $(basename $0) sessionname [windowname] [-v] [-c command1 command2] ...
+
+                    [-w windowname1]
+                        [-v] [-c command1 command2]...
+
+                    [-w windowname2]
+                        [-v] [-c command1 command2]...
+
+       Parameters:
+
+            sessionname     if provided, tmux will use this as session identifier
+                            (Default: given by tmux)
+
+            windowname      defines, what the first window in the new session
+                            is called (Default: given by tmux)
+
+            -w windowname   to start a new window
+
+            -v              to define, that all splits for this window should have
+                            a vertical layout (else horizontal)
+
+            command1, command2, ...
+                            the commands, that should be executed under this
+                            specific window
+                            0(If no command is given, the current shell will be used)
+
+"
+}
+
+#===============================================================================
+# help text, if the function is called with any kind of parameter
+#===============================================================================
 function isCtlArg {
     local me=`grep -e ^- <<< "$1"`
     local ret=0
@@ -13,9 +49,8 @@ function isCtlArg {
     fi
 }
 
-if [ $# != 0 ]; then 
 
-    # echo " "
+if [ $# != 0 ]; then
 
     seditor="${SHELL}"
     layout="h"
@@ -23,13 +58,30 @@ if [ $# != 0 ]; then
     first=1
     cnt=$#
 
-    command="tmux new ";
+    command="tmux -u new ";
 
-    if [ $(isCtlArg "$1") == "nope" ]; then 
+    if [ $(isCtlArg "$1") == "nope" ]; then
         command=$command"-s'$1' "
         session_name="$1"
-        ((first=2)) 
+        ((first=2))
+    else
+        print_help
+        exit;
     fi
+
+    if [ -n "${TMUX}" ]; then
+        cmd="tmux -u switch-client -t \"${session_name}\""
+    else
+        cmd="tmux -u attach -t \"${session_name}\""
+    fi
+    echo $cmd
+    res=$(eval "$cmd && echo \"success\" || echo \"fail\"")
+
+    if [[ "$res" == "success" ]]; then
+        echo "attach to existing" $cmd
+        exit;
+    fi
+
 
     # create Session
     #--------------------------------------------------------------------------
@@ -40,12 +92,12 @@ if [ $# != 0 ]; then
     # echo $command
     eval $command
 
-    if [[ -z ${session_name} ]]; then 
-        session_name=`tmux ls -F '#{session_created} #{session_name}' | sort | tail -n 1 | cut -d ' ' -f 2-`
+    if [[ -z ${session_name} ]]; then
+        session_name=`tmux -u ls -F '#{session_created} #{session_name}' | sort | tail -n 1 | cut -d ' ' -f 2-`
         # echo "session created: " $session_name
     fi
 
-    command='tmux ' 
+    command='tmux -u '
 
     # echo "--------------------------------------------";
     # echo " process commands "
@@ -62,12 +114,12 @@ if [ $# != 0 ]; then
         eval "arg=\"\${$i}\""
         # echo ">   arg $i is: $arg"
 
-        if [[ $(isCtlArg "$arg") == "yep" ]]; then 
+        if [[ $(isCtlArg "$arg") == "yep" ]]; then
             # echo ">>  is Ctl command"
 
             if [[ "$arg" == "-w" ]]; then
-                # echo ">>> create new window" 
-                if [[ $panes -gt 1 ]]; then 
+                # echo ">>> create new window"
+                if [[ $panes -gt 1 ]]; then
                     # echo ">>> has $panes panes"
                     if [[ "$layout" == "v" ]]; then
                         # echo ">>> layout vertical"
@@ -95,16 +147,16 @@ if [ $# != 0 ]; then
                 command=$command" \; rename-window -t '$session_name' '"$arg"'"
             elif [[ $mode == 1 ]]; then
                 if [[ $panes == 0 ]]; then
-                    command=$command" \; respawn-pane -k -t '$session_name:' '"$arg"'"                                              
+                    command=$command" \; respawn-pane -k -t '$session_name:' '"$arg"'"
                 else
-                    command=$command"\; split-pane -t '$session_name' '$arg' "    
+                    command=$command"\; split-pane -t '$session_name' '$arg' "
                 fi
                 ((panes++))
             fi
         fi
     done
-    
-    if [[ $panes -gt 1 ]]; then 
+
+    if [[ $panes -gt 1 ]]; then
         # echo ">>> has $panes panes"
         if [[ "$layout" == "v" ]]; then
             # echo ">>> layout vertical"
@@ -119,49 +171,18 @@ if [ $# != 0 ]; then
     # echo " Lets Gooooo !! "
     # echo "--------------------------------------------"
     # echo $command
-    
+
     command=$command" \; select-window -t '$session_name:0' "
 
     # echo $command
     eval $command
 
     if [ -n "${TMUX}" ]; then
-        tmux switch-client -t "${session_name}"
+        tmux -u switch-client -t "${session_name}"
     else
-        tmux attach -t "${session_name}"
+        tmux -u attach -t "${session_name}"
     fi
- 
 else
-
-#===============================================================================
-# help text, if the function is called with any kind of parameter
-#===============================================================================
-echo "usage: $(basename $0) [sessionname] [windowname] [-v] [-c command1 command2] ...
-
-                    [-w windowname1] 
-                        [-v] [-c command1 command2]... 
-
-                    [-w windowname2] 
-                        [-v] [-c command1 command2]... 
-
-       Parameters:
-
-            sessionname     if provided, tmux will use this as session identifier
-                            (Default: given by tmux)
-
-            windowname      defines, what the first window in the new session 
-                            is called (Default: given by tmux)
-
-            -w windowname   to start a new window
-
-            -v              to define, that all splits for this window should have
-                            a vertical layout (else horizontal)
-
-            command1, command2, ...
-                            the commands, that should be executed under this 
-                            specific window
-                            0(If no command is given, the current shell will be used)
-
-"
+    print_help
 fi
-
+exit;
